In [1]:
import numpy as np
import pandas as pd

1) How likely is it that you roll doubles when rolling two dice?

In [5]:
n_trials = nrows = 10_000
n_dice = ncols = 2
#then we need to use random choice

#this was my example:
#rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
#rolls


rolls = np.random.choice([1,2,3,4,5,6], size = (10_000, 2))
rolls

array([[2, 3],
       [2, 1],
       [2, 3],
       ...,
       [5, 2],
       [4, 4],
       [3, 1]])

In [6]:
dice_rolls_2 = pd.DataFrame(rolls)
dice_rolls_2

0  1
0     2  3
1     2  1
2     2  3
3     5  3
4     6  3
...  .. ..
9995  2  6
9996  2  2
9997  5  2
9998  4  4
9999  3  1

[10000 rows x 2 columns]

In [7]:
doubles = dice_rolls_2[0] == dice_rolls_2[1]
doubles

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996     True
9997    False
9998     True
9999    False
Length: 10000, dtype: bool

In [8]:
probably_doubles = doubles.mean()
probably_doubles

0.1666

#2 If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [12]:
n_trials = 8
n_sims = 10000
#im making 1 = head and 2 = tails

#flips = np.random.choice([1,2], n_trials * n_sims).reshape(n_sims, n_trials)
#flips

flips = np.random.choice([1,2], size = (n_sims, n_trials))
flips

array([[1, 2, 2, ..., 1, 2, 2],
       [2, 1, 2, ..., 1, 2, 2],
       [2, 2, 1, ..., 1, 2, 1],
       ...,
       [2, 2, 2, ..., 2, 2, 1],
       [2, 1, 2, ..., 2, 2, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [13]:
flips2=pd.DataFrame(flips)
flips2

0  1  2  3  4  5  6  7
0     1  2  2  1  2  1  2  2
1     2  1  2  2  2  1  2  2
2     2  2  1  1  2  1  2  1
3     2  1  2  2  1  2  1  2
4     1  1  2  2  2  1  2  1
...  .. .. .. .. .. .. .. ..
9995  2  2  2  1  1  2  1  2
9996  1  1  2  1  1  2  1  2
9997  2  2  2  2  2  2  2  1
9998  2  1  2  2  1  2  2  1
9999  1  1  1  2  1  1  1  1

[10000 rows x 8 columns]

In [29]:
same_3_flips = (flips == 1).sum(axis=1) == 3
same_3_flips

array([False, False,  True, ..., False,  True, False])

In [30]:
same_3_flips.mean()

0.221

In [32]:
greater_than_3 = (flips == 1).sum(axis=1) >3
greater_than_3

array([ True,  True, False, ..., False, False, False])

In [33]:
greater_than_3.mean()

0.6384

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup.

Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards 
I drive past both have data science students on them?

In [37]:
n_trials = 2
n_sims = 10_000

billboard = np.random.choice(['web_dev', 'Data_science'],n_trials * n_sims).reshape(n_sims, n_trials)
billboard

array([['web_dev', 'web_dev'],
       ['Data_science', 'web_dev'],
       ['web_dev', 'web_dev'],
       ...,
       ['Data_science', 'web_dev'],
       ['Data_science', 'Data_science'],
       ['Data_science', 'Data_science']], dtype='<U12')

In [42]:
billboard2 = pd.DataFrame(billboard)
billboard2.columns = ["first_billb", "second_billb"]
billboard2

first_billb  second_billb
0          web_dev       web_dev
1     Data_science       web_dev
2          web_dev       web_dev
3          web_dev  Data_science
4          web_dev       web_dev
...            ...           ...
9995       web_dev       web_dev
9996       web_dev       web_dev
9997  Data_science       web_dev
9998  Data_science  Data_science
9999  Data_science  Data_science

[10000 rows x 2 columns]

In [44]:
both_data_sci = (billboard2.first_billb == 'Data_science') & (billboard2.second_billb == 'Data_science')
both_data_sci

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998     True
9999     True
Length: 10000, dtype: bool

In [45]:
both_data_sci.mean()

0.2419

Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [53]:
n_trials = 5 #becasue of a reg. school week is 5 days 
n_sims = 10_000


poptarts = np.random.normal(3,1.5, size = (n_sims, n_trials))
rounded_pop = poptarts.round()
rounded_pop

array([[ 4.,  5.,  2.,  3.,  2.],
       [ 2.,  2.,  2.,  3.,  4.],
       [ 7.,  3.,  3.,  4.,  4.],
       ...,
       [ 3.,  3.,  5.,  1.,  5.],
       [ 2.,  3.,  3.,  0.,  6.],
       [ 3.,  3.,  2.,  5., -0.]])

In [55]:
poptarts_on_friday = rounded_pop.sum(axis=1) < 17
poptarts_on_friday.mean()

0.6724

In [ ]:
#Compare Heights

a)Men have an average height of 178 cm and standard deviation of 8cm.

b)Women have a mean of 170, sd = 6cm.

c)Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [57]:

men = np.random.normal(178,8, size = 10_000)
men

array([174.84730314, 171.90699681, 195.13968114, ..., 192.16688495,
       183.4867623 , 175.10958457])

In [59]:
Women = np.random.normal(170,6, size = 10_000)
Women

array([171.59503446, 169.21912872, 168.6926626 , ..., 162.06503058,
       169.82950326, 175.65341677])

In [67]:
Overall_height = pd.DataFrame({"men_avg":men, "Women_avg":Women})
Overall_height

men_avg   Women_avg
0     174.847303  171.595034
1     171.906997  169.219129
2     195.139681  168.692663
3     161.050288  172.264541
4     172.831480  165.782677
...          ...         ...
9995  175.594585  167.516173
9996  173.691937  163.122980
9997  192.166885  162.065031
9998  183.486762  169.829503
9999  175.109585  175.653417

[10000 rows x 2 columns]

In [69]:
Height_women_taller = Overall_height.Women_avg > Overall_height.men_avg

Height_women_taller

0       False
1       False
2       False
3        True
4       False
        ...  
9995    False
9996    False
9997    False
9998    False
9999     True
Length: 10000, dtype: bool

In [70]:
Height_women_taller.mean()

0.2108

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
 
 
What is the probability that we observe an installation issue within the first 150 students that download anaconda?



How likely is it that 450 students all download anaconda without an issue?

In [31]:
n_trials = n_cols = students
n_sims = n_rows = num_of_sims
    
    installs = np.random.choice([0,1], p=[1/250, 249/250], size=(n_rows, n_cols))
    

IndentationError: unexpected indent (2214907762.py, line 4)

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

In [73]:
n_trials = 3
#three days a week that we didnt see the truck 
n_sims = 10_000

food_trucks = np.random.choice([0,1], p=[.3,.7], size=(n_sims, n_trials))
food_trucks

array([[1, 0, 0],
       [1, 1, 0],
       [0, 1, 1],
       ...,
       [1, 1, 1],
       [0, 1, 1],
       [1, 0, 1]])

In [77]:
no_show_trucks = food_trucks.sum(axis=1) == 0
no_show_trucks

array([False, False, False, ..., False, False, False])

In [78]:
no_show_trucks.mean()

0.0276

In [ ]:
##How likely is it that a food truck will show up sometime this week?

In [79]:
n_trials = 7
#7 days a week 
n_sims = 10_000

food_trucks = np.random.choice([0,1], p=[.3,.7], size=(n_sims, n_trials))
food_trucks

array([[1, 1, 1, ..., 1, 0, 1],
       [1, 0, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [0, 0, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 1, 1, 0]])

In [ ]:
#make it greater than 0 since its only sometime this week 

In [82]:
Just_one_day_food_truck = food_trucks.sum(axis=1)>=0

In [83]:
Just_one_day_food_truck.mean()

0.9999

If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

two have the same BIRTHDAY, the size must be eaither the 23 or the other numbers, im assuming 

In [3]:
n_trials = 2

n_sims = 23

#1 equals one birthday #2 is another birthday 
birthdays = np.random.choice((1,2),n_trials * n_sims).reshape(n_sims, n_trials)
birthdays

array([[2, 1],
       [2, 2],
       [2, 2],
       [1, 1],
       [2, 2],
       [2, 1],
       [1, 1],
       [2, 2],
       [2, 1],
       [2, 1],
       [1, 1],
       [1, 2],
       [2, 2],
       [1, 1],
       [1, 1],
       [1, 2],
       [1, 2],
       [2, 2],
       [1, 2],
       [1, 1],
       [1, 1],
       [1, 2],
       [2, 2]])

In [8]:
bdays = pd.DataFrame(birthdays)
bdays

0  1
0   2  1
1   2  2
2   2  2
3   1  1
4   2  2
5   2  1
6   1  1
7   2  2
8   2  1
9   2  1
10  1  1
11  1  2
12  2  2
13  1  1
14  1  1
15  1  2
16  1  2
17  2  2
18  1  2
19  1  1
20  1  1
21  1  2
22  2  2

In [11]:
double_bdays = bdays[0] == bdays[1]
double_bdays

0     False
1      True
2      True
3      True
4      True
5     False
6      True
7      True
8     False
9     False
10     True
11    False
12     True
13     True
14     True
15    False
16    False
17     True
18    False
19     True
20     True
21    False
22     True
dtype: bool

In [12]:
double_bdays.mean()

0.6086956521739131

In [15]:
bday = np.random.randint(1,365, (10_000,23))
bday

array([[150, 184, 327, ..., 220,  72, 288],
       [175,  39, 180, ..., 234, 293,  50],
       [282, 210,  36, ..., 115,  12, 191],
       ...,
       [ 39, 180, 347, ...,   3,  57, 213],
       [ 45, 146,  55, ...,  27,  69, 101],
       [ 36, 150,  45, ..., 152, 271, 168]])

In [17]:
bday_df = pd.DataFrame(bday)
bday_df

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0     150  184  327   92  184   25  228  340  247  134  ...  349   73  223   
1     175   39  180  348   28   13  257  313  179   80  ...  181   87   27   
2     282  210   36  301    4  117  264  227   94  134  ...  132  296  248   
3     273  167   78  360  105  134  335  363   97   85  ...  250   31  327   
4     331   15  224  353  244   89  108  339  132  144  ...  340  118  159   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  178  343  174  197  239   10  114  191   89  220  ...  264  342  195   
9996  200  139   88  150  180  242  229   67   18  140  ...  360  193  110   
9997   39  180  347   95   22  190  252  291   41  102  ...  198  217  307   
9998   45  146   55  342  271   10  134   61  126  362  ...   41   74  101   
9999   36  150   45  218  122  148  309  142  314  273  ...  125   30  283   

       16   17   18   19   20   21   22  
0      29  156  162  318  220   72  288  
1     336   74   76  200  234  293   50  
2     291  243  308   52  115   12  191  
3     159  114  138  111   73  319    7  
4     166   34  267   26   36  122  226  
...   ...  ...  ...  ...  ...  ...  ...  
9995  118  195  146  360  167  264  213  
9996  215  331  103  283  324  162  335  
9997  115  103  201  189    3   57  213  
9998   80  197   40   34   27   69  101  
9999  158  271  346  357  152  271  168  

[10000 rows x 23 columns]

In [20]:
bday2 = np.random.randint(1,365, (10_000,20))
bday2

array([[307, 346, 112, ..., 103, 329, 169],
       [129,  58, 315, ..., 338,  63,  14],
       [ 49, 226,  29, ..., 228, 194, 120],
       ...,
       [244, 324, 200, ...,  82, 313, 283],
       [ 82, 110, 196, ...,  16, 159, 222],
       [335, 118, 200, ...,  49, 328, 274]])

In [22]:
bday2_df = pd.DataFrame(bday2)
bday2_df

0    1    2    3    4    5    6    7    8    9    10   11   12   13  \
0     307  346  112  248   49  334  162  230  174  196  153  254  326  286   
1     129   58  315   81  222  338   20  101  142  239  345  237  340  143   
2      49  226   29   74  135  181  102  334    7  303   66  229  212   10   
3      61  337  220  145   29   61  203  269  315  151  291   52  209  235   
4     313  188  241  311  323  131  136   34  302  113  210  185  198  194   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995   61  208  319  329   29  151   79  112  285   77  220  316  134   17   
9996  232    8    6  319  257  222  132  165  239   12   92  295  193  125   
9997  244  324  200  292  275  120  360  215   34  212    4  137  237  224   
9998   82  110  196  223  327  104   28  101  252  289  259  199  172   71   
9999  335  118  200  142  358  125  129  118  152  227   33   98  114  333   

       14   15   16   17   18   19  
0     242   68  309  103  329  169  
1      98  324  177  338   63   14  
2      93  204   13  228  194  120  
3      76  309  129  321  157  280  
4      22  122  161  319  288  188  
...   ...  ...  ...  ...  ...  ...  
9995    9  238   33   21   26  200  
9996  279  280  120  185   29  208  
9997  161   47  238   82  313  283  
9998  165  144   32   16  159  222  
9999  318  106  205   49  328  274  

[10000 rows x 20 columns]

In [24]:
bday3 = np.random.randint(1,365, (10_000,40))
bday3

array([[158, 348, 153, ..., 344,  29,  17],
       [ 61, 344,  40, ..., 274, 124, 303],
       [170, 281, 257, ..., 186,  38, 221],
       ...,
       [178,  24, 255, ..., 302, 310, 287],
       [144, 329, 290, ...,  66, 237,  44],
       [ 17, 223,  34, ..., 307, 184, 278]])

In [26]:
bday3_df = pd.DataFrame(bday3)
bday3_df

0    1    2    3    4    5    6    7    8    9   ...   30   31   32  \
0     158  348  153  333  363  351  278  355  209  289  ...  363  348  213   
1      61  344   40  125  184  184  168  340  278  319  ...  161  280  274   
2     170  281  257   94  270   96  169  238  100   13  ...  287  234  216   
3     353  266   53  187  107  341  219   29  218  111  ...  124  154  260   
4     222  231  114  107  112  152  140   67  354  234  ...   46  139  260   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  316   83  243  317  318  289   13  277   40  202  ...  340  191  364   
9996  353  343  329   79  115  178  361  138  111  316  ...  173   72   19   
9997  178   24  255  226  188  294    3  183  327  281  ...  259  118  363   
9998  144  329  290  141   88   98  272   29  231  235  ...   94  271  281   
9999   17  223   34  328  241  162   99  199  160  316  ...   83   24  242   

       33   34   35   36   37   38   39  
0     191  206   12  253  344   29   17  
1     284  295  209   70  274  124  303  
2      14  101  286  243  186   38  221  
3     247  320  157   15  174  235  237  
4     347  195   87   33  120   81  110  
...   ...  ...  ...  ...  ...  ...  ...  
9995  317  109   13  150  167   59  343  
9996  181  303  191  175  293  247  207  
9997   30  305  189  135  302  310  287  
9998   31  297  136  293   66  237   44  
9999  147  301  186  144  307  184  278  

[10000 rows x 40 columns]