In [1]:
import numpy as np
import pandas as pd

#1 How likely is it that you roll doubles when rolling two dice?

In [4]:
n_trials = nrows = 10_000
n_dice = ncols = 2
#then we need to use random choice

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls


array([[6, 4],
       [6, 1],
       [6, 2],
       ...,
       [2, 6],
       [5, 6],
       [2, 5]])

In [7]:
dice_rolls_2 = pd.DataFrame(rolls)
dice_rolls_2

0  1
0     6  4
1     6  1
2     6  2
3     6  2
4     4  2
...  .. ..
9995  1  4
9996  1  4
9997  2  6
9998  5  6
9999  2  5

[10000 rows x 2 columns]

In [10]:
doubles = dice_rolls_2[0] == dice_rolls_2[1]
doubles

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [12]:
prob_doubles = doubles.mean()
prob_doubles

0.1692

#2 If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [16]:
n_trials = 8
n_sims = 10000
#im making 1 to be head and 2 tails#
flips = np.random.choice([1,2], n_trials * n_sims).reshape(n_sims, n_trials)
flips

array([[1, 1, 2, ..., 1, 2, 1],
       [1, 2, 2, ..., 1, 1, 2],
       [2, 2, 2, ..., 1, 2, 1],
       ...,
       [2, 1, 2, ..., 2, 2, 1],
       [2, 1, 2, ..., 2, 1, 2],
       [2, 2, 1, ..., 2, 1, 2]])

In [19]:
flips2=pd.DataFrame(flips)
flips2

0  1  2  3  4  5  6  7
0     1  1  2  2  2  1  2  1
1     1  2  2  1  2  1  1  2
2     2  2  2  2  1  1  2  1
3     1  2  2  2  1  2  1  2
4     1  2  2  2  1  2  1  2
...  .. .. .. .. .. .. .. ..
9995  1  2  2  1  1  2  2  1
9996  2  1  2  2  2  2  2  2
9997  2  1  2  2  2  2  2  1
9998  2  1  2  2  1  2  1  2
9999  2  2  1  2  2  2  1  2

[10000 rows x 8 columns]

In [29]:
same_3_flips = (flips == 1).sum(axis=1) == 3
same_3_flips

array([False, False,  True, ..., False,  True, False])

In [30]:
same_3_flips.mean()

0.221

In [32]:
greater_than_3 = (flips == 1).sum(axis=1) >3
greater_than_3

array([ True,  True, False, ..., False, False, False])

In [33]:
greater_than_3.mean()

0.6384

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup.

Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards 

I drive past both have data science students on them?

In [37]:
n_trials = 2
n_sims = 10_000

billboard = np.random.choice(['web_dev', 'Data_science'],n_trials * n_sims).reshape(n_sims, n_trials)
billboard

array([['web_dev', 'web_dev'],
       ['Data_science', 'web_dev'],
       ['web_dev', 'web_dev'],
       ...,
       ['Data_science', 'web_dev'],
       ['Data_science', 'Data_science'],
       ['Data_science', 'Data_science']], dtype='<U12')

In [42]:
billboard2 = pd.DataFrame(billboard)
billboard2.columns = ["first_billb", "second_billb"]
billboard2

first_billb  second_billb
0          web_dev       web_dev
1     Data_science       web_dev
2          web_dev       web_dev
3          web_dev  Data_science
4          web_dev       web_dev
...            ...           ...
9995       web_dev       web_dev
9996       web_dev       web_dev
9997  Data_science       web_dev
9998  Data_science  Data_science
9999  Data_science  Data_science

[10000 rows x 2 columns]

In [44]:
both_data_sci = (billboard2.first_billb == 'Data_science') & (billboard2.second_billb == 'Data_science')
both_data_sci

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998     True
9999     True
Length: 10000, dtype: bool

In [45]:
both_data_sci.mean()

0.2419

Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [53]:
n_trials = 5 #becasue of a reg. school week is 5 days 
n_sims = 10_000


poptarts = np.random.normal(3,1.5, size = (n_sims, n_trials))
rounded_pop = poptarts.round()
rounded_pop

array([[ 4.,  5.,  2.,  3.,  2.],
       [ 2.,  2.,  2.,  3.,  4.],
       [ 7.,  3.,  3.,  4.,  4.],
       ...,
       [ 3.,  3.,  5.,  1.,  5.],
       [ 2.,  3.,  3.,  0.,  6.],
       [ 3.,  3.,  2.,  5., -0.]])

In [55]:
poptarts_on_friday = rounded_pop.sum(axis=1) < 17
poptarts_on_friday.mean()

0.6724

In [ ]:
#Compare Heights

a)Men have an average height of 178 cm and standard deviation of 8cm.

b)Women have a mean of 170, sd = 6cm.

c)Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [57]:

men = np.random.normal(178,8, size = 10_000)
men

array([174.84730314, 171.90699681, 195.13968114, ..., 192.16688495,
       183.4867623 , 175.10958457])

In [59]:
Women = np.random.normal(170,6, size = 10_000)
Women

array([171.59503446, 169.21912872, 168.6926626 , ..., 162.06503058,
       169.82950326, 175.65341677])

In [67]:
Overall_height = pd.DataFrame({"men_avg":men, "Women_avg":Women})
Overall_height

men_avg   Women_avg
0     174.847303  171.595034
1     171.906997  169.219129
2     195.139681  168.692663
3     161.050288  172.264541
4     172.831480  165.782677
...          ...         ...
9995  175.594585  167.516173
9996  173.691937  163.122980
9997  192.166885  162.065031
9998  183.486762  169.829503
9999  175.109585  175.653417

[10000 rows x 2 columns]

In [69]:
Height_women_taller = Overall_height.Women_avg > Overall_height.men_avg

Height_women_taller

0       False
1       False
2       False
3        True
4       False
        ...  
9995    False
9996    False
9997    False
9998    False
9999     True
Length: 10000, dtype: bool

In [70]:
Height_women_taller.mean()

0.2108

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
 
 
What is the probability that we observe an installation issue within the first 150 students that download anaconda?



How likely is it that 450 students all download anaconda without an issue?

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

In [73]:
n_trials = 3
#three days a week that we didnt see the truck 
n_sims = 10_000

food_trucks = np.random.choice([0,1], p=[.3,.7], size=(n_sims, n_trials))
food_trucks

array([[1, 0, 0],
       [1, 1, 0],
       [0, 1, 1],
       ...,
       [1, 1, 1],
       [0, 1, 1],
       [1, 0, 1]])

In [77]:
no_show_trucks = food_trucks.sum(axis=1) == 0
no_show_trucks

array([False, False, False, ..., False, False, False])

In [78]:
no_show_trucks.mean()

0.0276

In [ ]:
##How likely is it that a food truck will show up sometime this week?

In [79]:
n_trials = 7
#7 days a week 
n_sims = 10_000

food_trucks = np.random.choice([0,1], p=[.3,.7], size=(n_sims, n_trials))
food_trucks

array([[1, 1, 1, ..., 1, 0, 1],
       [1, 0, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [0, 0, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 1, 1, 0]])

In [ ]:
#make it greater than 0 since its only sometime this week 

In [82]:
Just_one_day_food_truck = food_trucks.sum(axis=1)>0

In [83]:
Just_one_day_food_truck.mean()

0.9999

If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

#two have the same BIRTHDAY, the size must be eaither the 23 or the other numbers im assuming 