In [2]:
import numpy as np
import pandas as pd

1) How likely is it that you roll doubles when rolling two dice?

In [5]:
n_trials = nrows = 10_000
n_dice = ncols = 2
#then we need to use random choice

#this was my example:
#rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
#rolls


rolls = np.random.choice([1,2,3,4,5,6], size = (10_000, 2))
rolls

array([[2, 3],
       [2, 1],
       [2, 3],
       ...,
       [5, 2],
       [4, 4],
       [3, 1]])

In [6]:
dice_rolls_2 = pd.DataFrame(rolls)
dice_rolls_2

0  1
0     2  3
1     2  1
2     2  3
3     5  3
4     6  3
...  .. ..
9995  2  6
9996  2  2
9997  5  2
9998  4  4
9999  3  1

[10000 rows x 2 columns]

In [7]:
doubles = dice_rolls_2[0] == dice_rolls_2[1]
doubles

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996     True
9997    False
9998     True
9999    False
Length: 10000, dtype: bool

In [8]:
probably_doubles = doubles.mean()
probably_doubles

0.1666

2) If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [12]:
n_trials = 8
n_sims = 10000
#im making 1 = head and 2 = tails

#flips = np.random.choice([1,2], n_trials * n_sims).reshape(n_sims, n_trials)
#flips

flips = np.random.choice([1,2], size = (n_sims, n_trials))
flips

array([[1, 2, 2, ..., 1, 2, 2],
       [2, 1, 2, ..., 1, 2, 2],
       [2, 2, 1, ..., 1, 2, 1],
       ...,
       [2, 2, 2, ..., 2, 2, 1],
       [2, 1, 2, ..., 2, 2, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [13]:
flips2=pd.DataFrame(flips)
flips2

0  1  2  3  4  5  6  7
0     1  2  2  1  2  1  2  2
1     2  1  2  2  2  1  2  2
2     2  2  1  1  2  1  2  1
3     2  1  2  2  1  2  1  2
4     1  1  2  2  2  1  2  1
...  .. .. .. .. .. .. .. ..
9995  2  2  2  1  1  2  1  2
9996  1  1  2  1  1  2  1  2
9997  2  2  2  2  2  2  2  1
9998  2  1  2  2  1  2  2  1
9999  1  1  1  2  1  1  1  1

[10000 rows x 8 columns]

In [29]:
same_3_flips = (flips == 1).sum(axis=1) == 3
same_3_flips

array([False, False,  True, ..., False,  True, False])

In [30]:
same_3_flips.mean()

0.221

In [32]:
greater_than_3 = (flips == 1).sum(axis=1) >3
greater_than_3

array([ True,  True, False, ..., False, False, False])

In [33]:
greater_than_3.mean()

0.6384

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup.

Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards 
I drive past both have data science students on them?

In [3]:
n_trials = 2
n_sims = 10_000

# WD = 0 , DS = 1 

billboard =np.random.choice([0,1], size = (n_sims, n_trials), p= [0.75, 0.25])


In [4]:
billboard2 = pd.DataFrame(billboard)
billboard2.columns = ["first_billb", "second_billb"]
billboard2

first_billb  second_billb
0               1             0
1               0             0
2               1             0
3               1             0
4               1             0
...           ...           ...
9995            0             0
9996            1             1
9997            0             0
9998            0             0
9999            1             0

[10000 rows x 2 columns]

In [7]:
both_data_sci = (billboard.sum(axis = 1) ==2)

#notes: the 2 is by adding the rows because a 2 would equal two DS bb's 

In [8]:
both_data_sci.mean()

0.0635

Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [10]:
n_trials = 5 #becasue of a reg. school week is 5 days 
n_sims = 10_000

#np.random.normal(average, STD, size = ())


poptarts = np.random.normal(3,1.5, size = (n_sims, n_trials))
rounded_pop = poptarts.round()
rounded_pop

array([[ 3.,  2.,  2.,  2.,  3.],
       [ 2.,  3.,  6.,  5.,  4.],
       [ 3.,  3.,  3.,  3.,  2.],
       ...,
       [ 3.,  2.,  1.,  5.,  2.],
       [ 4.,  5.,  3.,  6.,  4.],
       [ 5.,  3.,  4.,  6., -0.]])

In [11]:
poptarts_on_friday = rounded_pop.sum(axis=1) < 17
poptarts_on_friday

array([ True, False,  True, ...,  True, False, False])

In [12]:
poptarts_on_friday.mean()

0.6697

Compare hights 

a)Men have an average height of 178 cm and standard deviation of 8cm.

b)Women have a mean of 170, sd = 6cm.

c)Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [13]:

men = np.random.normal(178,8, size = 10_000)
men

array([176.04647419, 180.29266094, 181.37608295, ..., 172.71842211,
       186.19749756, 182.21953861])

In [14]:
Women = np.random.normal(170,6, size = 10_000)
Women

array([154.13869845, 178.1962198 , 174.65310536, ..., 164.42447133,
       166.66754384, 179.69683581])

In [15]:
Overall_height = pd.DataFrame({"Men_avg":men, "Women_avg":Women})
Overall_height

Men_avg   Women_avg
0     176.046474  154.138698
1     180.292661  178.196220
2     181.376083  174.653105
3     181.297956  172.285968
4     179.855720  172.384979
...          ...         ...
9995  169.219484  164.630466
9996  190.404575  163.274703
9997  172.718422  164.424471
9998  186.197498  166.667544
9999  182.219539  179.696836

[10000 rows x 2 columns]

In [17]:
Height_women_taller = Overall_height.Women_avg > Overall_height.Men_avg

Height_women_taller

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [18]:
Height_women_taller.mean()

0.2105

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
 
 
What is the probability that we observe an installation issue within the first 150 students that download anaconda?



How likely is it that 450 students all download anaconda without an issue?

In [23]:
#0 = no issue, 1= issues 

install = np.random.choice([0,1], size = (10_000 , 50), p = [249/250, 1/250])
install
    

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [26]:
no_issues = install.sum(axis=1) == 0

In [27]:
#no issues for 50 students 
no_issues.mean()

0.8212

In [28]:
install_100 = np.random.choice([0,1], size = (10_000 , 100), p = [249/250, 1/250])
install_100

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [30]:
no_issues1 = (install_100.sum(axis=1) == 0)
no_issues1

array([ True,  True, False, ...,  True,  True,  True])

In [31]:
#no issues for 100 students 
no_issues1.mean()

0.6782

In [32]:
install_150 = np.random.choice([0,1], size = (10_000 , 150), p = [249/250, 1/250])
install_150

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [34]:
no_issues2 = (install_150.sum(axis=1) == 0)
no_issues2

array([ True, False, False, ...,  True,  True, False])

In [36]:
#probability of 150 students 
no_issues2.mean()

0.552

In [37]:
install_450 = np.random.choice([0,1], size = (10_000 , 450), p = [249/250, 1/250])
install_450

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [39]:
no_issues3 = (install_450.sum(axis=1) == 0)
no_issues3

array([False, False, False, ..., False,  True, False])

In [40]:
# the probability of 450 
no_issues3.mean()

0.1616

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

personal notes - how unlikely is it that we wont see the truck in three days?

In [41]:
n_trials = 3
#three days a week that we didnt see the truck 
n_sims = 10_000

#0 = no truck, 1 = truck showed up 
food_trucks = np.random.choice([0,1], p=[.3,.7], size=(n_sims, n_trials))
food_trucks

array([[1, 0, 1],
       [1, 1, 0],
       [0, 1, 0],
       ...,
       [1, 1, 0],
       [1, 1, 1],
       [0, 0, 1]])

In [42]:
#in order to measure how unlikely it is to not see the trucks in three days straight the row needs to == 0 
#because 0 == no truck 

no_show_trucks = food_trucks.sum(axis=1) == 0
no_show_trucks

array([False, False, False, ..., False, False, False])

In [43]:
no_show_trucks.mean()

0.0277

In [44]:
##How likely is it that a food truck will show up sometime this week?

In [45]:
n_trials = 7
#7 days a week 
n_sims = 10_000

food_trucks = np.random.choice([0,1], p=[.3,.7], size=(n_sims, n_trials))
food_trucks

array([[1, 1, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 0, 1, 1],
       [1, 0, 1, ..., 0, 0, 1],
       ...,
       [1, 1, 1, ..., 1, 0, 0],
       [0, 1, 1, ..., 1, 1, 0],
       [1, 1, 0, ..., 1, 1, 1]])

In [ ]:
#make it greater than 0 since its only sometime this week and it can equal one or more 

In [46]:
Just_one_day_food_truck = food_trucks.sum(axis=1)>=0

In [47]:
Just_one_day_food_truck.mean()

1.0

If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?



In [49]:
#the range (1, 366) means the birthdays for 365 days in a year 


birthday = np.random.choice(range(1,366), size = (10000,23))
birthday

array([[267,  51, 350, ...,  62, 236, 120],
       [161, 294,  31, ..., 180,  98,  25],
       [ 91, 356, 213, ..., 252,   1, 301],
       ...,
       [199,   4, 164, ..., 287, 363, 189],
       [  7,  87,   8, ..., 200, 278, 143],
       [242, 329, 275, ..., 277, 353,  72]])

In [51]:
#remember the .nunique needs to be with a dataframe & this function counts the number of unique instances in the rows 
pd.DataFrame(birthday).nunique(axis = 1)

0       22
1       23
2       21
3       23
4       22
        ..
9995    23
9996    23
9997    22
9998    23
9999    22
Length: 10000, dtype: int64

In [52]:
pd.DataFrame(birthday).nunique(axis = 1).mean()

22.3198

In [53]:
(pd.DataFrame(birthday).nunique(axis = 1) <23)

0        True
1       False
2        True
3       False
4        True
        ...  
9995    False
9996    False
9997     True
9998    False
9999     True
Length: 10000, dtype: bool

In [54]:
#this is for 23 people
(pd.DataFrame(birthday).nunique(axis = 1) <23).mean()

0.5058

In [55]:
birthday1 = np.random.choice(range(1,366), size = (10000,20))
birthday1

array([[ 51,  14, 147, ...,  41, 345, 128],
       [275,  51, 364, ..., 333,  26,  87],
       [208, 280, 185, ..., 218, 118, 220],
       ...,
       [  3, 161, 183, ..., 216, 344, 365],
       [326,  10,  13, ..., 224, 239, 349],
       [165, 324,  42, ...,  86,  46,  27]])

In [58]:
pd.DataFrame(birthday1).nunique(axis=1) < 20


0       False
1        True
2       False
3        True
4        True
        ...  
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [59]:
#this is for 20 people 
(pd.DataFrame(birthday1).nunique(axis=1) < 20).mean()

0.4132

In [60]:
birthday2 = np.random.choice(range(1,366), size = (10000,40))
birthday2

array([[118,  94, 318, ..., 276, 149, 297],
       [350, 321, 152, ..., 364, 120,  65],
       [ 88,  89, 104, ...,  25, 235, 162],
       ...,
       [338,  86, 295, ...,  73, 331, 209],
       [318,  36, 134, ...,  89, 316,  40],
       [205, 233, 282, ...,  51, 310,  90]])

In [61]:
pd.DataFrame(birthday2).nunique(axis=1)<40

0        True
1       False
2       False
3        True
4        True
        ...  
9995    False
9996     True
9997     True
9998     True
9999     True
Length: 10000, dtype: bool

In [62]:
#this is for 40 people 
(pd.DataFrame(birthday2).nunique(axis=1)<40).mean()

0.8903

Madge Duel 

Imagine your wizard has 6d4 health points and you have spells that do 6d4 damage. "6d4" means rolling six 4-sided dice and summing the result.

Your opposing mage has 4d6 health points and spells that do 4d6. "4d6" means rolling four six-sided dice and summing the result.

Exercises
Simulate mage duels to answer who is the more powerful mage?



Before running simulations, do you have a hypothesis of which mage will win? Do you have a hunch? Write it down. This is your first exercise.

Im not too sure who will win but i think it might be the opposing mage? maybe because of the more sides the dice has?

In [ ]:
#Simulate 10 mage duels. Is there a clear winner? Run that 10 duel simulation again. Was the answer similar?

In [87]:
(np.random.choice([1,2,3,4], size = (10 , 6)).sum(axis=1)).sum()

167

In [86]:
(np.random.choice([1,2,3,4,5,6], size = (10 , 4)).sum(axis=1)).sum()

152

In [ ]:
#Do the results change much at 100 duels?

In [82]:
(np.random.choice([1,2,3,4], size = (100 , 6)).sum(axis=1)).sum()

1518

In [83]:
(np.random.choice([1,2,3,4,5,6], size = (100 , 4)).sum(axis=1)).sum()

1331

In [81]:
#Now, simulate 10,000 mage duels. Is there a clear winner?

In [103]:
(np.random.choice([1,2,3,4], size = (10_000 , 6)).sum(axis=1)).sum()

149894

In [108]:
(np.random.choice([1,2,3,4,5,6], size = (10_000 , 4)).sum(axis=1)).sum()

139437

In [ ]:
#looks like i am the winner!